package com.hiddless.java_fx;

import com.hiddless.java_fx.database.SingletonDBConnection;
import com.hiddless.java_fx.utils.SpecialColor;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

public class HelloApplication extends Application {

    @Override
    public void start(Stage stage) throws IOException {

        initializeDatabase();

        FXMLLoader fxmlLoader = new FXMLLoader(HelloApplication.class.getResource("view/login.fxml"));
        Parent parent= fxmlLoader.load();
        stage.setTitle("User Management Login Page");
        stage.setScene(new Scene(parent));
        stage.show();
    }

    /////////////////////////////////////////////////////////////////////////////
    /// DATABASE

    private void initializeDatabase() {
        try {
            Connection conn = SingletonDBConnection.getInstance().getConnection();
            Statement stmt = conn.createStatement();

            String createTableSQL = """
                -- User login
                CREATE TABLE IF NOT EXISTS users (
                    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    username VARCHAR(50) NOT NULL UNIQUE,
                    password VARCHAR(255) NOT NULL,
                    email VARCHAR(100) NOT NULL UNIQUE
                );
                
                
                    CREATE TABLE receipts (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        receipt_number VARCHAR(50) NOT NULL UNIQUE,
                        receipt_date DATE NOT NULL,
                        tax_number VARCHAR(20) NOT NULL,
                        company_name VARCHAR(100) NOT NULL,
                        customer_name VARCHAR(100) NOT NULL,
                        description TEXT,
                        created_by VARCHAR(100) NOT NULL,
                        account_code VARCHAR(50) NOT NULL,
                     
                       
                        receipt_type VARCHAR(20) NOT NULL CHECK (receipt_type IN ('Payment', 'Collection', 'Cost', 'Salary')),
                        amount DECIMAL(10,2) NOT NULL,
                        vat_rate DECIMAL(5,2) NOT NULL,
                        total_amount DECIMAL(10,2) NOT NULL,
                 
                        payment_type VARCHAR(20) NOT NULL CHECK (payment_type IN ('Cash', 'Credit Card', 'Transfer', 'check')),
                    
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    );   
                """;
            stmt.execute(createTableSQL);

            String insertDataSQL = """
                MERGE INTO users (id, username, password, email)
                KEY(id) VALUES (1, 'Hiddles', 'hiddles', 'hiddles@gmail.com');
                """;
            stmt.execute(insertDataSQL);

            System.out.println(SpecialColor.CYAN+"H2DB Database created successfully and data added."+SpecialColor.RESET);

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    public static void main(String[] args) {
        launch();
    }
}