
CREATE DATABASE user_management;


USE user_management;


CREATE TABLE IF NOT EXISTS users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE
);

-- ###################################################################################################################

-- Insert
MERGE INTO users (id, username, password, email) KEY(id) VALUES (1,'Hiddles','323123','hiddles@gmail.com' )

-- Select
select * FROM users;

-- Find User
SELECT  *  FROM users WHERE username="Hiddles" AND "323123";

-- Update
UPDATE users SET username="Hiddles81", password="321836", email="hiddles81@gmail.com" WHERE id=1;

-- delete
DELETE FROM users  WHERE id=1;